version: 0.2
        
phases:
  install:
    runtime-versions:
      dotnet: 6.0
  pre_build:
    commands:
      - dotnet restore Amax.InsurancePro.Web/Amax.InsurancePro.Web.csproj
  build:
    commands:
      - dotnet build Amax.InsurancePro.Web/Amax.InsurancePro.Web.csproj
  post_build:
    commands:
      - dotnet publish -c Release -o ./app/ Amax.InsurancePro.Web/Amax.InsurancePro.Web.csproj
artifacts:
  files:
    - '**/*'
