version: 0.2

env:
  variables:
    PROJECT: Amax.InsurancePro.Web
    DOTNET_CORE_RUNTIME: 3.1

phases:
  install:
    runtime-versions:
      dotnet: ${DOTNET_CORE_RUNTIME}
      
  pre_build:
    commands:
      - echo "dotnet restore"
      - dotnet restore

  build:
    commands:
      - echo "dotnet build"
      - dotnet build -c Release

  post_build:
    commands:
      - echo "publish the code"
      - dotnet publish -c Release -r linux-x64 -o ./build_output ./src/${PROJECT}/${PROJECT}.csproj --self-contained false

artifacts:
  files:
    - '**/*'
  base-directory: ./build_output
  discard-paths: no
