version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
  pre_build:
    commands:
      - echo "Restoring NuGet packages"
      - dotnet restore
  build:
    commands:
      - echo "Building the .NET project"
      - dotnet build --configuration Release
  post_build:
    commands:
      - echo "Publishing artifacts"
      - dotnet publish -c Release -o ./publish
artifacts:
  files:
    - ./publish
    - ./appspec.yml
    - ./Scripts
  discard-paths: yes

cache:
  paths:
    - ~/.nuget/packages
