version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
    commands:
      - echo Installing .NET SDK...
      - dotnet tool install -g Amazon.ElasticBeanstalk.Tools
  pre_build:
    commands:
      - echo This pre_build phase ... ran at `date`
  build:
    commands:
      - echo Build started at `date`
      - dotnet restore Amax-Web.sln
      - dotnet build Amax-Web.sln
      - dotnet publish Amax-Web.sln -c Release -o target
      - echo Build completed at `date`
  post_build:
    commands:
      - echo This pre_build phase ... ran at `date`
artifacts:
  files:
    - target/**/*

