version: 0.2

phases:
install:
commands:
•  echo Restore NuGet packages...

•  nuget restore Amax.Web.sln

pre_build:
commands:
•  echo Build started on `date`

•  echo Compiling the ASP.NET MVC application...

build:
commands:
•  msbuild Amax.Web.sln /p:Configuration=Release /p:OutputPath=./build_output

post_build:
commands:
•  echo Build completed on `date`

•  echo Packaging the application...

•  &packaging 'WebDeploy package creation'

•  mkdir ./packaged_artifacts

•  msbuild Amax.Web.sln /t:Package /p:PackageLocation=./packaged_artifacts/


artifacts:
files:
•  ./packaged_artifacts/**/*

discard-paths: yes
